EXP - 10 Principal Component Analysis

In [2]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


In [3]:
X = np.array([
    [4, 11],
    [8, 4],
    [13, 5],
    [7, 14]
])

scaler = StandardScaler()
X_std = scaler.fit_transform(X)

In [5]:
pca = PCA(n_components=1)
Z_reduced = pca.fit_transform(X_std)

In [6]:
print("Original Data:\n", X)

print("\nMean of each feature (used in PCA):\n", pca.mean_)

print("\nPrincipal Component (Eigenvector):\n", pca.components_)
print("\nExplained Variance:\n", pca.explained_variance_)
print("\nReduced Data (1D projection):\n", Z_reduced)

Original Data:
 [[ 4 11]
 [ 8  4]
 [13  5]
 [ 7 14]]

Mean of each feature (used in PCA):
 [-4.16333634e-17  0.00000000e+00]

Principal Component (Eigenvector):
 [[-0.70710678  0.70710678]]

Explained Variance:
 [2.15067471]

Reduced Data (1D projection):
 [[ 1.29849983]
 [-0.76613088]
 [-1.68696902]
 [ 1.15460007]]
